#!/usr/bin/env python3
"""
FLUX ISA v3 Conformance Vector Runner

Loads v3 conformance vectors from conformance-vectors-v3.json and executes them
against the FluxVMv3 from test_conformance_v3.py.

Usage:
    PYTHONPATH=. python3 run_v3_conformance.py              # Run all v3 vectors
    PYTHONPATH=. python3 run_v3_conformance.py --json       # JSON output
    PYTHONPATH=. python3 run_v3_conformance.py --markdown   # Markdown table

Generated by Datum for CONF-001 integration.
"""

import argparse
import json
import os
import struct
import sys
import time
from datetime import datetime, timezone
from pathlib import Path

# Import v3 VM
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

# We need the v3 VM from test_conformance_v3.py
# Since we can't directly import classes from test files, we'll inline the VM
# by importing the module properly

import importlib.util
spec = importlib.util.spec_from_file_location(
    "test_conformance_v3",
    os.path.join(os.path.dirname(os.path.abspath(__file__)), "test_conformance_v3.py")
)
test_v3 = importlib.util.module_from_spec(spec)
# Need conformance_core for push_imm32, store_addr, load_addr
spec.loader.exec_module(test_v3)

run_v3 = test_v3.run_v3
run_v3_expect_error = test_v3.run_v3_expect_error


def load_v3_vectors(filepath):
    """Load v3 conformance vectors from JSON file."""
    with open(filepath) as f:
        data = json.load(f)
    return data.get("vectors", [])


def run_single_vector(vector):
    """Run a single v3 conformance vector. Returns (passed, actual_stack, actual_flags, error, duration_ms)."""
    bytecode_hex = vector["bytecode_hex"]
    # Parse hex string to bytes
    bytecode = bytes.fromhex(bytecode_hex.replace(" ", ""))
    initial_stack = vector.get("initial_stack", [])

    expected_stack = vector.get("expected_stack", [])
    expected_error = vector.get("expected_error", None)
    name = vector.get("name", "unknown")

    start = time.monotonic()
    try:
        if expected_error:
            run_v3_expect_error(bytecode, expected_error, initial_stack)
            elapsed = (time.monotonic() - start) * 1000
            return True, [], 0, "", elapsed
        else:
            stack, flags = run_v3(bytecode, initial_stack)
            elapsed = (time.monotonic() - start) * 1000

            # Check stack match
            if stack != expected_stack:
                return False, stack, flags, f"Stack mismatch: expected {expected_stack}, got {stack}", elapsed

            # Check flags if specified (not -1)
            expected_flags = vector.get("expected_flags", -1)
            if expected_flags != -1 and flags != expected_flags:
                return False, stack, flags, f"Flags mismatch: expected {expected_flags}, got {flags}", elapsed

            return True, stack, flags, "", elapsed

    except Exception as e:
        elapsed = (time.monotonic() - start) * 1000
        err_str = str(e)
        if expected_error and expected_error in err_str:
            return True, [], 0, "", elapsed
        return False, [], 0, err_str, elapsed


def run_all_vectors(vectors):
    """Run all vectors and return results."""
    results = []
    for v in vectors:
        passed, actual_stack, actual_flags, error, duration = run_single_vector(v)
        results.append({
            "name": v.get("name", "unknown"),
            "category": v.get("category", "unknown"),
            "v3_only": v.get("v3_only", False),
            "passed": passed,
            "expected_stack": v.get("expected_stack", []),
            "actual_stack": actual_stack,
            "expected_flags": v.get("expected_flags", -1),
            "actual_flags": actual_flags,
            "error": error,
            "duration_ms": round(duration, 3),
            "description": v.get("description", "")
        })
    return results


def print_terminal(results, vectors):
    """Print results to terminal."""
    passed = sum(1 for r in results if r["passed"])
    total = len(results)
    v3_only_passed = sum(1 for r in results if r["passed"] and r["v3_only"])
    v3_only_total = sum(1 for r in results if r["v3_only"])
    compat_passed = sum(1 for r in results if r["passed"] and not r["v3_only"])
    compat_total = sum(1 for r in results if not r["v3_only"])

    print()
    print("=" * 72)
    print(f"  FLUX ISA v3 CONFORMANCE TEST RESULTS")
    print(f"  Generated: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S')} UTC")
    print(f"  Runner: FluxVMv3 (Python reference)")
    print("=" * 72)
    print(f"  Total:  {passed}/{total} passed ({passed/total*100:.1f}%)")
    print(f"  v3-only: {v3_only_passed}/{v3_only_total} passed")
    print(f"  Backward compat: {compat_passed}/{compat_total} passed")
    print("=" * 72)

    # Category breakdown
    categories = {}
    for r in results:
        cat = r["category"]
        if cat not in categories:
            categories[cat] = {"passed": 0, "total": 0, "failed": []}
        categories[cat]["total"] += 1
        if r["passed"]:
            categories[cat]["passed"] += 1
        else:
            categories[cat]["failed"].append(r["name"])

    print(f"\n{'Category':<25s} {'Passed':>7s} {'Total':>7s} {'Rate':>8s}")
    print("-" * 50)
    for cat, data in sorted(categories.items()):
        rate = f"{data['passed']/data['total']*100:.0f}%" if data['total'] > 0 else "N/A"
        mark = "✓" if data['passed'] == data['total'] else "✗"
        print(f"  {cat:<23s} {data['passed']:>5d}/{data['total']:<5d} {rate:>6s} {mark}")

    # Show failures
    failures = [r for r in results if not r["passed"]]
    if failures:
        print(f"\n{'=' * 72}")
        print(f"  FAILURES ({len(failures)})")
        print(f"{'=' * 72}")
        for f in failures:
            print(f"  ✗ {f['name']:<40s} {f['error'][:50]}")
    else:
        print(f"\n  ALL TESTS PASSED 🎉")

    print()


def output_json(results, filepath=None):
    """Output results as JSON."""
    passed = sum(1 for r in results if r["passed"])
    output = {
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "runner": "FluxVMv3 (Python reference)",
        "source": "conformance-vectors-v3.json",
        "total": len(results),
        "passed": passed,
        "pass_rate": f"{passed/len(results)*100:.1f}%",
        "results": results
    }

    json_str = json.dumps(output, indent=2)
    if filepath:
        with open(filepath, "w") as f:
            f.write(json_str)
        print(f"Results written to {filepath}")
    else:
        print(json_str)


def output_markdown(results, filepath=None):
    """Output results as Markdown table."""
    passed = sum(1 for r in results if r["passed"])
    lines = [
        "# FLUX ISA v3 Conformance Results",
        "",
        f"**Timestamp:** {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S')} UTC  ",
        f"**Runner:** FluxVMv3 (Python reference)  ",
        f"**Source:** `conformance-vectors-v3.json`  ",
        f"**Result:** {passed}/{len(results)} passed ({passed/len(results)*100:.1f}%)  ",
        "",
        "## Summary by Category",
        "",
        "| Category | Passed | Total | Rate |",
        "|----------|--------|-------|------|",
    ]

    categories = {}
    for r in results:
        cat = r["category"]
        if cat not in categories:
            categories[cat] = {"passed": 0, "total": 0}
        categories[cat]["total"] += 1
        if r["passed"]:
            categories[cat]["passed"] += 1

    for cat, data in sorted(categories.items()):
        rate = f"{data['passed']/data['total']*100:.0f}%"
        mark = "✓" if data['passed'] == data['total'] else "✗"
        lines.append(f"| {cat} | {data['passed']}/{data['total']} | {data['total']} | {rate} {mark} |")

    failures = [r for r in results if not r["passed"]]
    if failures:
        lines.append("")
        lines.append("## Failures")
        lines.append("")
        lines.append("| Test Name | Category | Error |")
        lines.append("|-----------|----------|-------|")
        for f in failures:
            lines.append(f"| `{f['name']}` | {f['category']} | {f['error'][:60]} |")

    output = "\n".join(lines)
    if filepath:
        with open(filepath, "w") as f:
            f.write(output)
        print(f"Results written to {filepath}")
    else:
        print(output)


def main():
    parser = argparse.ArgumentParser(description="FLUX ISA v3 Conformance Runner")
    parser.add_argument("--json", action="store_true", help="JSON output")
    parser.add_argument("--markdown", action="store_true", help="Markdown output")
    parser.add_argument("--output", type=str, metavar="FILE", help="Write output to file")
    parser.add_argument("--vectors", type=str, default=None, help="Path to v3 vectors JSON")

    args = parser.parse_args()

    # Find vectors file
    if args.vectors:
        vectors_path = args.vectors
    else:
        script_dir = os.path.dirname(os.path.abspath(__file__))
        vectors_path = os.path.join(script_dir, "conformance-vectors-v3.json")

    if not os.path.exists(vectors_path):
        print(f"Error: Vectors file not found: {vectors_path}")
        sys.exit(1)

    vectors = load_v3_vectors(vectors_path)
    print(f"Loaded {len(vectors)} v3 conformance vectors from {vectors_path}")

    results = run_all_vectors(vectors)

    if args.json:
        output_json(results, args.output)
    elif args.markdown:
        output_markdown(results, args.output)
    else:
        print_terminal(results, vectors)

    # Exit code
    passed = sum(1 for r in results if r["passed"])
    sys.exit(0 if passed == len(results) else 1)


if __name__ == "__main__":
    main()
