// Code generated by cross_runtime/go_adapter.py — DO NOT EDIT.
//
// Cross-runtime conformance tests for the FLUX Unified ISA.
// This file runs the same test vectors that the Python VM adapter
// executes and asserts identical register state and halt behavior.
//
// To run:
//   go test -v -run TestCrossRuntime .

package vm_test

import (
	"testing"

	"github.com/flux-labs/flux/pkg/vm"
)

// testVector mirrors the JSON test-vector schema in
// cross_runtime/unified_test_vectors.json.
type testVector struct {
	Name        string
	Description string
	Bytecode    []byte
	Category    string
	Slow        bool

	ExpHalted  bool
	ExpError   bool
	ExpRegs    map[string]int32
	InitRegs   map[string]int32
}

// vectors holds every cross-runtime test vector.
var vectors = []testVector {
	{
		Name:        "branch-call-ret",
		Description: "CALL subroutine doubles R1: 21 -> 42 via ADD R1,R1,R1 then RET",
		Bytecode:    []byte{
		0x18, 0x01, 0x15, 0x00, 0x4a, 0x00, 0x01, 0x00, 0x00, 0x20, 0x01, 0x01,
		0x01, 0x02,
	},
		Category:    "branch",
		Slow:        false,

		ExpHalted:  true,
		ExpError:   false,
		ExpRegs:    map[string]int32{"R1": int32(42)},
		InitRegs:   nil,
	}
}

// TestCrossRuntime runs every vector on the Go VM and checks
// that the resulting register state and halt/error flags match
// the expected values from the Python reference runtime.
func TestCrossRuntime(t *testing.T) {
	for _, tv := range vectors {
		t.Run(tv.Name, func(t *testing.T) {
			if tv.Slow {
				t.Skip("slow test")
			}

			// Build VM and load initial registers
			m := vm.New()
			for reg, val := range tv.InitRegs {
				idx := parseRegIndex(reg)
				m.SetReg(idx, int(val))
			}

			// Execute
			m.Load(tv.Bytecode)
			m.Run()

			// Check halted / error
			if m.Halted() != tv.ExpHalted {
				t.Errorf("halted: expected %v, got %v", tv.ExpHalted, m.Halted())
			}
			if m.Error() != tv.ExpError {
				t.Errorf("error: expected %v, got %v", tv.ExpError, m.Error())
			}

			// Check registers
			for reg, exp := range tv.ExpRegs {
				idx := parseRegIndex(reg)
				act := m.GetReg(idx)
				if act != int32(exp) {
					t.Errorf("%s: expected %d, got %d", reg, exp, act)
				}
			}
		})
	}
}

// parseRegIndex converts "R0", "R1", ... to an integer index.
func parseRegIndex(s string) int {
	if len(s) > 1 && (s[0] == 'R' || s[0] == 'r') {
		idx := 0
		for _, c := range s[1:] {
			idx = idx*10 + int(c-'0')
		}
		return idx
	}
	idx := 0
	for _, c := range s {
		idx = idx*10 + int(c-'0')
	}
	return idx
}
