#!/usr/bin/env python3
"""Go VM adapter for cross-runtime conformance testing.

Generates a self-contained Go test file that imports ``pkg/vm`` and
executes every vector from ``unified_test_vectors.json``, asserting
identical results to the Python reference runtime.

The generated file embeds all test vectors as Go structs so the Go
test runner can execute them without any external data files.

Usage (standalone)::

    python go_adapter.py                           # generate flux_vm_test.go
    python go_adapter.py --output /tmp/vm_test.go  # custom output path
    python go_adapter.py --pkg-path github.com/flux-labs/flux/pkg/vm

Usage (as library)::

    from go_adapter import GoAdapter
    adapter = GoAdapter()
    go_code = adapter.generate(vectors, pkg_import)
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path
from typing import Any, Dict, List, Optional


# ===================================================================
#  Go code generator
# ===================================================================

_GO_TEST_TEMPLATE = """\
// Code generated by cross_runtime/go_adapter.py — DO NOT EDIT.
//
// Cross-runtime conformance tests for the FLUX Unified ISA.
// This file runs the same test vectors that the Python VM adapter
// executes and asserts identical register state and halt behavior.
//
// To run:
//   go test -v -run TestCrossRuntime .

package vm_test

import (
\t"testing"

\t"{pkg_import}"
)

// testVector mirrors the JSON test-vector schema in
// cross_runtime/unified_test_vectors.json.
type testVector struct {{
\tName        string
\tDescription string
\tBytecode    []byte
\tCategory    string
\tSlow        bool

\tExpHalted  bool
\tExpError   bool
\tExpRegs    map[string]int32
\tInitRegs   map[string]int32
}}

// vectors holds every cross-runtime test vector.
var vectors = []testVector {{
{vector_entries}
}}

// TestCrossRuntime runs every vector on the Go VM and checks
// that the resulting register state and halt/error flags match
// the expected values from the Python reference runtime.
func TestCrossRuntime(t *testing.T) {{
\tfor _, tv := range vectors {{
\t\tt.Run(tv.Name, func(t *testing.T) {{
\t\t\tif tv.Slow {{
\t\t\t\tt.Skip("slow test")
\t\t\t}}

\t\t\t// Build VM and load initial registers
\t\t\tm := vm.New()
\t\t\tfor reg, val := range tv.InitRegs {{
\t\t\t\tidx := parseRegIndex(reg)
\t\t\t\tm.SetReg(idx, int(val))
\t\t\t}}

\t\t\t// Execute
\t\t\tm.Load(tv.Bytecode)
\t\t\tm.Run()

\t\t\t// Check halted / error
\t\t\tif m.Halted() != tv.ExpHalted {{
\t\t\t\tt.Errorf("halted: expected %v, got %v", tv.ExpHalted, m.Halted())
\t\t\t}}
\t\t\tif m.Error() != tv.ExpError {{
\t\t\t\tt.Errorf("error: expected %v, got %v", tv.ExpError, m.Error())
\t\t\t}}

\t\t\t// Check registers
\t\t\tfor reg, exp := range tv.ExpRegs {{
\t\t\t\tidx := parseRegIndex(reg)
\t\t\t\tact := m.GetReg(idx)
\t\t\t\tif act != int32(exp) {{
\t\t\t\t\tt.Errorf("%s: expected %d, got %d", reg, exp, act)
\t\t\t\t}}
\t\t\t}}
\t\t}})
\t}}
}}

// parseRegIndex converts "R0", "R1", ... to an integer index.
func parseRegIndex(s string) int {{
\tif len(s) > 1 && (s[0] == 'R' || s[0] == 'r') {{
\t\tidx := 0
\t\tfor _, c := range s[1:] {{
\t\t\tidx = idx*10 + int(c-'0')
\t\t}}
\t\treturn idx
\t}}
\tidx := 0
\tfor _, c := range s {{
\t\tidx = idx*10 + int(c-'0')
\t}}
\treturn idx
}}
"""


class GoAdapter:
    """Generate Go test code from unified test vectors."""

    def __init__(
        self,
        pkg_import: str = "github.com/flux-labs/flux/pkg/vm",
        skip_slow: bool = True,
    ) -> None:
        self.pkg_import = pkg_import
        self.skip_slow = skip_slow

    # ------------------------------------------------------------------
    #  Helpers
    # ------------------------------------------------------------------

    @staticmethod
    def parse_bytecode_hex(hex_str: str) -> List[int]:
        """Parse space-separated hex bytes into a list of ints."""
        s = hex_str.strip().replace(" ", "")
        if len(s) % 2:
            s = "0" + s
        return [int(s[i:i+2], 16) for i in range(0, len(s), 2)]

    @staticmethod
    def _go_byte_array(byte_values: List[int]) -> str:
        """Format a list of byte values as a Go byte slice literal."""
        if not byte_values:
            return "nil"
        hex_strs = [f"0x{b:02x}" for b in byte_values]
        # Wrap at ~12 items per line for readability
        lines = []
        for i in range(0, len(hex_strs), 12):
            chunk = ", ".join(hex_strs[i:i+12])
            lines.append(f"\t\t{chunk}")
        inner = ",\n".join(lines)
        return f"[]byte{{\n{inner},\n\t}}"

    @staticmethod
    def _go_int32_map(reg_dict: Dict[str, int]) -> str:
        """Format a register map as a Go map literal."""
        if not reg_dict:
            return "nil"
        entries = ", ".join(
            f'"{k}": int32({v})' for k, v in sorted(reg_dict.items())
        )
        return f"map[string]int32{{{entries}}}"

    # ------------------------------------------------------------------
    #  Vector entry generation
    # ------------------------------------------------------------------

    def _format_vector_entry(self, vec: dict) -> str:
        """Generate a single Go struct literal for a test vector."""
        name = vec.get("name", "")
        desc = vec.get("description", "").replace('"', '\\"')
        category = vec.get("category", "")
        tags = vec.get("tags", [])
        is_slow = "slow" in tags

        bc = self.parse_bytecode_hex(vec.get("bytecode_hex", ""))
        bc_go = self._go_byte_array(bc)

        exp_final = vec.get("expected_final", {})
        exp_regs = exp_final.get("registers", {})
        exp_halted = exp_final.get("halted", False)
        exp_error = exp_final.get("error", False)

        init_regs = vec.get("initial_registers", {})
        init_regs_go = self._go_int32_map(init_regs)
        exp_regs_go = self._go_int32_map(exp_regs)

        return (
            f"\t{{\n"
            f'\t\tName:        "{name}",\n'
            f'\t\tDescription: "{desc}",\n'
            f'\t\tBytecode:    {bc_go},\n'
            f'\t\tCategory:    "{category}",\n'
            f"\t\tSlow:        {str(is_slow).lower()},\n"
            f"\n"
            f"\t\tExpHalted:  {str(exp_halted).lower()},\n"
            f"\t\tExpError:   {str(exp_error).lower()},\n"
            f"\t\tExpRegs:    {exp_regs_go},\n"
            f"\t\tInitRegs:   {init_regs_go},\n"
            f"\t}}"
        )

    # ------------------------------------------------------------------
    #  Main generation
    # ------------------------------------------------------------------

    def generate(self, vectors: List[dict]) -> str:
        """Generate the complete Go test file source code.

        Parameters
        ----------
        vectors : list[dict]
            List of test-vector dicts as loaded from
            ``unified_test_vectors.json``.

        Returns
        -------
        str
            Complete Go test file source code.
        """
        entries = []
        for vec in vectors:
            entry = self._format_vector_entry(vec)
            entries.append(entry)

        vector_entries = ",\n\n".join(entries)
        code = _GO_TEST_TEMPLATE.format(
            pkg_import=self.pkg_import,
            vector_entries=vector_entries,
        )
        return code

    # ------------------------------------------------------------------
    #  File I/O
    # ------------------------------------------------------------------

    def generate_and_write(
        self,
        vectors: List[dict],
        output_path: str = "flux_vm_test.go",
    ) -> str:
        """Generate Go test code and write to a file.

        Parameters
        ----------
        vectors : list[dict]
            List of test-vector dicts.
        output_path : str
            Filesystem path for the generated ``_test.go`` file.

        Returns
        -------
        str
            Absolute path of the written file.
        """
        code = self.generate(vectors)
        path = Path(output_path)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(code, encoding="utf-8")
        return str(path.resolve())


# ===================================================================
#  CLI
# ===================================================================

def _load_vectors(path: str) -> List[dict]:
    with open(path, "r", encoding="utf-8") as f:
        data = json.load(f)
    return data.get("vectors", data) if isinstance(data, dict) else data


def main(argv: Optional[List[str]] = None) -> int:
    parser = argparse.ArgumentParser(
        prog="go_adapter.py",
        description="Generate Go cross-runtime conformance test file",
    )
    parser.add_argument(
        "--vectors", default=None,
        help="Path to unified_test_vectors.json",
    )
    parser.add_argument(
        "--output", "-o", default=None,
        help="Output path for the generated Go test file",
    )
    parser.add_argument(
        "--pkg-path", default="github.com/flux-labs/flux/pkg/vm",
        help="Go import path for the VM package",
    )
    args = parser.parse_args(argv)

    # Locate vectors
    vectors_path = args.vectors
    if not vectors_path:
        candidates = [
            Path(__file__).parent / "unified_test_vectors.json",
            Path.cwd() / "unified_test_vectors.json",
        ]
        for c in candidates:
            if c.is_file():
                vectors_path = str(c)
                break
    if not vectors_path:
        print("ERROR: cannot find unified_test_vectors.json", file=sys.stderr)
        return 1

    vectors = _load_vectors(vectors_path)

    # Default output path: same directory as this script
    output_path = args.output
    if not output_path:
        output_path = str(Path(__file__).parent / "flux_vm_test.go")

    adapter = GoAdapter(pkg_import=args.pkg_path)
    written = adapter.generate_and_write(vectors, output_path)

    print(f"Generated Go test file: {written}")
    print(f"  Vectors: {len(vectors)}")
    print(f"  Package: {args.pkg_path}")
    print()
    print("To run:")
    print(f"  cd <go-module-root> && go test -v -run TestCrossRuntime .")

    return 0


if __name__ == "__main__":
    sys.exit(main())
